spring:
  jpa:
    hibernate:
     ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/loandb
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
